### ISSUE TITLE
语音转文字的时候错误 json: Unmarshal(nil *voice.ASRResponse)

### ISSUE THREAD

**Issue by SWBMESSI** [chenqinghe/baidu-ai-go-sdk#15]

**Comment by chenqinghe** [comment]
可以描述的再详细一点吗？

**Comment by SWBMESSI** [comment]
asr.go文件 是这个地方报错
var asrResponse *ASRResponse
	if err := resp.ToJSON(asrResponse); err != nil {
		fmt.Println("error here")
		return nil, err
	}

**Comment by SWBMESSI** [comment]
> 可以描述的再详细一点吗？

我找到原因了；是百度api的问题字段更换了 没有lan了 新增了 dev_pid

**Comment by chenqinghe** [comment]
fixed
