### ISSUE TITLE
Need to add example / demo directory

### ISSUE THREAD

**Issue by maxwell92** [chenqinghe/baidu-ai-go-sdk#2]
I think we should add an example or demo directory, helping people better understand use this api sdk faster.

**Comment by chenqinghe** [comment]
good suggestion! if you are interested in this. you can create new PR. i have to finish other features first, so i may not have enough time for the time being. if you can, that's very good. : P

**Comment by maxwell92** [comment]
ok, I would like to make some examples and maybe some feature code.  FYI you can write one short essay about this project after the main features are finished. Just scan the QR code as my Avatar, then I can help you post it.
